// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2jk8ac9WT0tYQnSBl1kpwc1rv6RwzBsI',
    appId: '1:210422833402:web:dca4e3bc287a96d34e6943',
    messagingSenderId: '210422833402',
    projectId: 'event-us-af71c',
    authDomain: 'event-us-af71c.firebaseapp.com',
    storageBucket: 'event-us-af71c.firebasestorage.app',
    measurementId: 'G-FR7TCNDXET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiwKqS4SvUfzcVjWbxHo2cASIeXHp-TWo',
    appId: '1:210422833402:android:b91e32574fb85b1e4e6943',
    messagingSenderId: '210422833402',
    projectId: 'event-us-af71c',
    storageBucket: 'event-us-af71c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2R0VwJrj23JW7-ahOGab3-SFd9F7MQZ0',
    appId: '1:210422833402:ios:ea26780a254c09264e6943',
    messagingSenderId: '210422833402',
    projectId: 'event-us-af71c',
    storageBucket: 'event-us-af71c.firebasestorage.app',
    iosBundleId: 'com.event.com.eventUs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2jk8ac9WT0tYQnSBl1kpwc1rv6RwzBsI',
    appId: '1:210422833402:web:c44f58d3481afb094e6943',
    messagingSenderId: '210422833402',
    projectId: 'event-us-af71c',
    authDomain: 'event-us-af71c.firebaseapp.com',
    storageBucket: 'event-us-af71c.firebasestorage.app',
    measurementId: 'G-0JKSXZEYJY',
  );
}
